#include "ninja_gen.hpp"
#include <fmt/core.h>

void NinjaGenerator::write(std::string code) {
    m_code += code;
}

void NinjaGenerator::writeln(std::string code) {
    write(code);
    write("\n");
}

void NinjaGenerator::generate() {
    auto& config = m_builder.config();
    writeln("# This file is @generated by Qobs: DO NOT EDIT!");
    writeln("ninja_required_version = 1.1");

    for (auto& file : m_builder.files()) {
        writeln(fmt::format("build {}: {}", file.path().string(),
                            file.path().string()));
    }
}
